module.exports = {
  // stories: ["../src/**/*.mdx", "../src/**/*.@(mdx|stories.@(js|jsx|ts|tsx))"],
  stories: ["../src/components/Alert/docs/Alert.stories.tsx",
    "../src/components/Alert/docs/UncontrolledAlert.stories.tsx",
    "../src/components/Accordion/docs/Accordion.stories.tsx",
    "../src/components/Accordion/docs/AccordionBody.stories.tsx",
    "../src/components/Activities/docs/Activity.stories.tsx",
    "../src/components/Badges/docs/Badge.stories.tsx",
    "../src/components/Breadcrumb/docs/Breadcrumb.stories.tsx",
    "../src/components/Buttons/docs/Button.stories.tsx",
    "../src/components/Cards/docs/Card.stories.tsx",
    "../src/components/Carousel/docs/Carousel.stories.tsx",
    "../src/components/Collapse/docs/Collapse.stories.tsx",
    "../src/components/Collapse/docs/UncontrolledCollapse.stories.tsx",
    "../src/components/Container/docs/Container.stories.tsx",
    "../src/components/Drawer/docs/Drawer.stories.tsx",
    "../src/components/Dropdowns/docs/Dropdown.stories.tsx",
    "../src/components/Fade/docs/Fade.stories.tsx",
    "../src/components/Grid/docs/Row.stories.tsx",
    "../src/components/Grid/docs/Col.stories.tsx",
    "../src/components/List/docs/List.stories.tsx",
    "../src/components/Modal/docs/Modal.stories.tsx",
    "../src/components/Nav/docs/Nav.stories.tsx",
    "../src/components/Panel/docs/Panel.stories.tsx",
    "../src/components/Placeholder/docs/Placheholder.stories.tsx",
    "../src/components/Progress/docs/Progress.stories.tsx",
    "../src/components/Pagination/docs/Pagination.stories.tsx",
    "../src/components/Spinner/docs/Spinner.stories.tsx",
    "../src/components/Typography/docs/Typography.stories.tsx",
    "../src/components/Tooltip/docs/Tooltip.stories.tsx",
    "../src/components/Toast/docs/Toast.stories.tsx",
    "../src/components/TabPane/docs/Tabpane.stories.tsx",
    "../src/components/Table/docs/ImsSimpleTable.stories.tsx",
    "../src/components/Table/docs/Table.stories.tsx",
    "../src/components/Popper/docs/Popover.stories.tsx",
    "../src/components/Forms/docs/*.stories.tsx",
  ],
  staticDirs: ["public"],

  addons: [
    "@storybook/addon-docs",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/preset-create-react-app",
    "@chromatic-com/storybook",
  ],

  framework: {
    name: "@storybook/react-webpack5",
    options: {},
  },

  docs: {
    autodocs: true,
  },
};
