name: s3 prod-deployment 

on:
  push:
    branches: [v2.x/production] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: yarn install
      
      - name: Production build
        run:  yarn build:production
        env:
          CI: false
      
      - name: Copy files to s3
        run: aws s3 sync ./build/ ${{ secrets.S3_PROD_BUCKET }}

      - name: Invalidate cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_PROD_DIST_ID }} \
            --paths "/*"

      # - name: Publishes changelogs
      #   uses: dmnemec/copy_file_to_another_repo_action@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source_file: 'changelog.md'
      #     destination_repo: 'ims-systems-00/ims-systems-userguide'
      #     destination_branch: 'master'
      #     destination_folder: '/'
      #     user_email: 'riadhossain7464@gmail.com'
      #     user_name: 'Riadhossain43'
      #     commit_message: 'Copied latest updates to documentation.'